dogcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('dogs/', views.dogs_index, name='dogs_index'),
    path('dogs/<int:dog_id>/', views.dogs_detail, name='dogs_detail'),
    path('dogs/create/', views.DogCreate.as_view(), name='dogs_create'),
    path('dogs/<int:pk>/update', views.DogUpdate.as_view(), name='dogs_update'),
    path('dogs/<int:pk>/delete', views.DogDelete.as_view(), name='dogs_delete'),
    path('dogs/<int:dog_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('dogs/<int:dog_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner'),
)

# Create your models here.

class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('toys_detail', kwargs={'pk': self.id})


class Dog(models.Model):
    name = models.CharField(max_length=250)
    breed = models.CharField(max_length=250)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    
    toys = models.ManyToManyField(Toy)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('dogs_detail', kwargs={'dog_id': self.id})

class Feeding(models.Model):
    # fields for the feeding model:
    date = models.DateField('feeding date')
    # meal will be represented as b, l or d
    meal = models.CharField(
        max_length=1, 
        choices=MEALS, 
        default=MEALS[0][0]
        )
    # one cat has many feedings
    dog = models.ForeignKey(
        Dog,
        on_delete=models.CASCADE
        )

    def __str__(self):
        return f"{self.get_meal_display()} at {self.date}"

    class Meta:
        ordering = ['-date']

main_app/forms.py
# import ModelForm class from django
from django.forms import ModelForm
from .models import Feeding

# feedingform inherits from modelform
class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Dog, Toy
from .forms import FeedingForm

# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def dogs_index(request):
    dogs = Dog.objects.all()
    return render(request, 'dogs/index.html', {'dogs': dogs})

def dogs_detail(request, dog_id):
    # query the database for a single dog obj
    dog = Dog.objects.get(id=dog_id)
    # exclude from our query all toys associated w current dog
    toys_dog_doesnt_have = Toy.objects.exclude(id__in = dog.toys.all().values_list('id'))
    # create instance of the feedingform
    feeding_form = FeedingForm()
    return render(request,
        'dogs/detail.html',
        { 'dog': dog, 'feeding_form': feeding_form, 'available_toys': toys_dog_doesnt_have }
    )
    # return a call to render the detail.html and context dict
    return render(request, 'dogs/detail.html', {'dog': dog})

def add_feeding(request, dog_id):
    # create feeding form and fice it the form data
    form = FeedingForm(request.POST)
    # validate the data
    if form.is_valid():
        # save the data
        # create the feeding butnot save it to the db yet
        new_feeding = form.save(commit=False)
        # attach the dog_id to the feeding BEFORE saving it to the db 
        new_feeding.dog_id = dog_id
        new_feeding.save()
    return redirect('dogs_detail', dog_id=dog_id)

def assoc_toy(request, dog_id, toy_id):
    # locate dog and .add the toy by its id
    Dog.objects.get(id=dog_id).toys.add(toy_id)
    return redirect('dogs_detail', dog_id=dog_id)

class DogCreate(CreateView):
    model = Dog
    fields = ['name', 'breed', 'description', 'age']

    # success_url = '/dogs/'

class DogUpdate(UpdateView):
    model = Dog
    fields = ['breed', 'description', 'age']

class DogDelete(DeleteView):
    model = Dog
    success_url = '/dogs/'

class ToyList(ListView):
    model = Toy

class ToyDetail(DetailView):
    model = Toy
 
class ToyCreate(CreateView):
    model = Toy
    fields = '__all__'

class ToyUpdate(UpdateView):
    model = Toy
    fields = ['name', 'color']

class ToyDelete(DeleteView):
    model = Toy
    success_url = '/toys/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1>About the Dog Collector</h1>
<hr>
<p>Hire The Dog Collector!</p>

{% endblock %}
    

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <title>Dog Collector</title>
</head>
<body>
   <header class="navbar-fixed">
       <nav>
           <div class="nav-wrapper">
              <ul>
                  <li>
                      <a href="{% url 'home' %}" class="left brand-logo">Dog Collector</a>
                  </li>
              </ul> 
              <ul class="right">
                  <li>
                      <a href="{% url 'about' %}">About</a>
                  </li>
                  <li>
                      <a href="{% url 'toys_create' %}">Add a Toy</a>
                    </li>
                  <li>
                      <a href="{% url 'toys_index' %}">View All Toys</a>
                    </li>
                  <li>
                      <a href="{% url 'dogs_create' %}">Add A Dog</a>
                  </li>
                  <li>
                      <a href="{% url 'dogs_index' %}">View All My Dogs</a>
                  </li>
              </ul>
           </div>
       </nav>
   </header>
   <main class="container">
      {% block content %}

      {% endblock %} 
   </main>
   <footer class="page-footer">
    <div class="right">All Rights Reserved &copy; <span id="year"></span> Dog Collector</div>
</footer>
<script>
    const spanEl = document.getElementById('year');
    spanEl.innerText = new Date().getFullYear();
</script>
</body>
</html>

main_app/templates/dogs/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Dog Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ dog.name }}</span>
        <p>Breed: {{ dog.breed }}</p>
        <p>Description: {{ dog.description }}</p>
        {% if dog.age > 0 %}
          <p>Age: {{ dog.age }}</p>
        {% else %}
          <p>Age: Puppy</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'dogs_update' dog.id %}">Edit</a>
        <a href="{% url 'dogs_delete' dog.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_feeding' dog.id %}" method="POST">
        {% csrf_token %}
        {{ feeding_form.as_p }}
        <input type="submit" class="btn" value="Add Feeding"/>
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Meal</th></tr>
      </thead>
      <tbody>
        {% for feeding in dog.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>


<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ dog.name }}'s Toys</h3>
    {% if dog.toys.count %}
      {% for toy in dog.toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{toy.color}}">
                {{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
    <h5>No Toys &#128532;</h5>
      <p>Go add some!</p>
    {% endif %}
  </div>

  <!-- available toys -->
  <div class="col s6">
    <h3>Available Toys</h3>
    {% if available_toys.count %}
      {% for toy in available_toys.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}</span>
        </div>

        <div class="card-action">
          <form action="{% url 'assoc_toy' dog.id toy.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn">Add</button>
          </form>
        </div>
      </div>

      {% endfor %}
    {% else %}
      <h5>{{ dog.name }} Already Has All The Available Toys</h5>
    {% endif %}
  </div>
</div>


<script>
    var dateEl = document.getElementById('id_date')
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });
    // meal dropdown
    var selectEl = document.getElementById('id_meal')
    M.FormSelect.init(selectEl)
</script>

{% endblock %}

main_app/templates/dogs/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Dog List</h1>
{% for dog in dogs %}
<a href="{% url 'dogs_detail' dog.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">
                {{ dog.name}}
            </span>
            <p>Breed: {{ dog.breed }}</p>
            <p>Description: {{ dog.description }}</p>
            {% if cat.age > 0 %}
            <p>Age: {{ dog.age }}</p>
            {% else %}
            <p>Age: Puppy</p>
            {% endif %}
        </div>
    </div>
</a>
{% endfor %}

{% endblock %}
    

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>Welcome To The Dog Collector</h1>
{% endblock %}

main_app/templates/main_app/dog_confirm_delete.html
{%extends '../base.html'%}
{% block content %}
    <h4>Are you sure you want to <span class="red-text">delete</span> <span class="teal-text">{{ object.name }}</span>?</h4>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete" class="btn">
        <a href="{% url 'dogs_detail' dog.id %}">Nevermind</a>
    </form>
{% endblock %}

main_app/templates/main_app/dog_form.html
{% extends '../base.html' %}
{% block content %}
    {% if object %}
    <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
    {% else %}
    <h1>Add A Dog</h1>
    {% endif %}
    <form action="" method="POST">
        {% csrf_token %}

        {{ form.as_table }}

        <input type="submit" value="Submit" class="btn">
    </form>
{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Toy</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'toys_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/toy_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ toy.name }}</span>
        <p>Color: {{ toy.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'toys_update' toy.id %}">Edit</a>
        <a href="{% url 'toys_delete' toy.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Toy</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/toy_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy List</h1>

{% for toy in toy_list %}
  <a href="{% url 'toys_detail' toy.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ toy.name }}</span>
            <p>Color: {{ toy.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}